### ISSUE TITLE
Running locally in a container when mounting volumes, I'm not getting a hot reload

### ISSUE THREAD

**Issue by rmoskal** [GoogleCloudPlatform/functions-framework-php#22]
Should I be?

**Comment by bshaffer** [comment]
Can you share your `docker run` command?

**Comment by bshaffer** [comment]
And your `Dockerfile`?

**Comment by rmoskal** [comment]
No worries. I'm using docker and docker-compose.  I'm just using your docker file:

```
FROM gcr.io/gae-runtimes/php73:php73_20191020_7_3_10_RC00


WORKDIR /srv

# NOTE: The entrypoint "/start", which starts up NGINX and PHP-FPM,
# is configured by creating a `.googleconfig/app_start.json` file with the
# contents:
#
#     {"entrypointContents": "CUSTOM_ENTRYPOINT"}
#
# We configure it to use the `router.php` file included in this package.
RUN mkdir .googleconfig && \
    echo '{"entrypointContents": "serve vendor/bin/router.php"}' > .googleconfig/app_start.json

# Copy over composer files and run "composer install"
COPY composer.* ./
COPY --from=composer:1 /usr/bin/composer /usr/local/bin
RUN composer install --no-dev

# Copy over all application files
COPY . .

# Set a runtime name (required by the base image)
ENV GAE_RUNTIME php73

```
With a vanilla docker-compose file, that I start with docker-compose up.

```
version: "3.0"
services:
  php:
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./app:/srv/app
    networks:
      - townz_db
networks:
  townz_db:
    external:
      name: agt_master_townz-database
```
I'm using the http call to kick off a batch php script.  My problem was that I was heavily editing the batch script and the changes would not be picked up by the http function unless I restarted the container. 

This was wrecking havoc with my development flow.

However, I eventually realized that I didn't need to use the http function to debug at all. I can just bash into the container and run the php script from the command line.

Still, would be a nice feature!
